hosts:
    # Scan IP address, networks or IP address rage. Examlpes:'172.16.3.0/24' or '172.16.3.10-20'
    net_address:
            - '172.16.3.0/24'
            - '172.16.2.100-105'

    # Login password for Linux system. a password list
    ssh_username: 'root'
    ssh_password: '1234@abcd.com'

    ssh_private_key: '/root/.ssh/id_rsa'

    commands:
            - 'hostname'
            - 'cat /etc/redhat-release'
            - 'dmidecode -s system-serial-number'
            - 'dmidecode -s system-manufacturer'
            - 'dmidecode -s system-product-name'
            - 'cat /sys/class/net/[^tsbvl]*/address'

    email: 'robbie_han@outlook.com'

    # Whether to send an email notification after the scan is completed, true or false.
    send_email: 'false'

    # Scan type consists of two parts, basic scan and enhanced scan, the default type is basic_scan.
    # basic_scan just running basic_scan to find online hosts.
    # enhanced_scan will be running os_scan and LoginExecution to get more info of online hosts.
    scan_type: 'basic_scan'

    # Support two authentication modes: password and private_key, and default is password.
    auth_type: 'private_key'







